// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["bluebubbles-policy"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "bluebubbles",
    artifactBasename: "api.js",
  });
}
export const isAllowedBlueBubblesSender: FacadeModule["isAllowedBlueBubblesSender"] = ((...args: any[]) =>
  loadFacadeModule()["isAllowedBlueBubblesSender"](
    ...args,
  )) as FacadeModule["isAllowedBlueBubblesSender"];
export const resolveBlueBubblesGroupRequireMention: FacadeModule["resolveBlueBubblesGroupRequireMention"] =
  ((...args: any[]) =>
    loadFacadeModule()["resolveBlueBubblesGroupRequireMention"](
      ...args,
    )) as FacadeModule["resolveBlueBubblesGroupRequireMention"];
export const resolveBlueBubblesGroupToolPolicy: FacadeModule["resolveBlueBubblesGroupToolPolicy"] =
  ((...args: any[]) =>
    loadFacadeModule()["resolveBlueBubblesGroupToolPolicy"](
      ...args,
    )) as FacadeModule["resolveBlueBubblesGroupToolPolicy"];
