// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["browser-runtime"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeObjectValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "browser",
    artifactBasename: "runtime-api.js",
  });
}
export const DEFAULT_AI_SNAPSHOT_MAX_CHARS: FacadeModule["DEFAULT_AI_SNAPSHOT_MAX_CHARS"] =
  loadFacadeModule()["DEFAULT_AI_SNAPSHOT_MAX_CHARS"];
export const DEFAULT_BROWSER_EVALUATE_ENABLED: FacadeModule["DEFAULT_BROWSER_EVALUATE_ENABLED"] =
  loadFacadeModule()["DEFAULT_BROWSER_EVALUATE_ENABLED"];
export const DEFAULT_VORA_BROWSER_COLOR: FacadeModule["DEFAULT_VORA_BROWSER_COLOR"] =
  loadFacadeModule()["DEFAULT_VORA_BROWSER_COLOR"];
export const DEFAULT_VORA_BROWSER_PROFILE_NAME: FacadeModule["DEFAULT_VORA_BROWSER_PROFILE_NAME"] =
  loadFacadeModule()["DEFAULT_VORA_BROWSER_PROFILE_NAME"];
export const DEFAULT_UPLOAD_DIR: FacadeModule["DEFAULT_UPLOAD_DIR"] =
  loadFacadeModule()["DEFAULT_UPLOAD_DIR"];
export const applyBrowserProxyPaths: FacadeModule["applyBrowserProxyPaths"] = ((...args: any[]) =>
  loadFacadeModule()["applyBrowserProxyPaths"](...args)) as FacadeModule["applyBrowserProxyPaths"];
export const browserAct: FacadeModule["browserAct"] = ((...args: any[]) =>
  loadFacadeModule()["browserAct"](...args)) as FacadeModule["browserAct"];
export const browserArmDialog: FacadeModule["browserArmDialog"] = ((...args: any[]) =>
  loadFacadeModule()["browserArmDialog"](...args)) as FacadeModule["browserArmDialog"];
export const browserArmFileChooser: FacadeModule["browserArmFileChooser"] = ((...args: any[]) =>
  loadFacadeModule()["browserArmFileChooser"](...args)) as FacadeModule["browserArmFileChooser"];
export const browserCloseTab: FacadeModule["browserCloseTab"] = ((...args: any[]) =>
  loadFacadeModule()["browserCloseTab"](...args)) as FacadeModule["browserCloseTab"];
export const browserConsoleMessages: FacadeModule["browserConsoleMessages"] = ((...args: any[]) =>
  loadFacadeModule()["browserConsoleMessages"](...args)) as FacadeModule["browserConsoleMessages"];
export const browserCreateProfile: FacadeModule["browserCreateProfile"] = ((...args: any[]) =>
  loadFacadeModule()["browserCreateProfile"](...args)) as FacadeModule["browserCreateProfile"];
export const browserDeleteProfile: FacadeModule["browserDeleteProfile"] = ((...args: any[]) =>
  loadFacadeModule()["browserDeleteProfile"](...args)) as FacadeModule["browserDeleteProfile"];
export const browserFocusTab: FacadeModule["browserFocusTab"] = ((...args: any[]) =>
  loadFacadeModule()["browserFocusTab"](...args)) as FacadeModule["browserFocusTab"];
export const browserHandlers: FacadeModule["browserHandlers"] = createLazyFacadeObjectValue(
  () => loadFacadeModule()["browserHandlers"] as object,
) as FacadeModule["browserHandlers"];
export const browserNavigate: FacadeModule["browserNavigate"] = ((...args: any[]) =>
  loadFacadeModule()["browserNavigate"](...args)) as FacadeModule["browserNavigate"];
export const browserOpenTab: FacadeModule["browserOpenTab"] = ((...args: any[]) =>
  loadFacadeModule()["browserOpenTab"](...args)) as FacadeModule["browserOpenTab"];
export const browserPdfSave: FacadeModule["browserPdfSave"] = ((...args: any[]) =>
  loadFacadeModule()["browserPdfSave"](...args)) as FacadeModule["browserPdfSave"];
export const browserProfiles: FacadeModule["browserProfiles"] = ((...args: any[]) =>
  loadFacadeModule()["browserProfiles"](...args)) as FacadeModule["browserProfiles"];
export const browserResetProfile: FacadeModule["browserResetProfile"] = ((...args: any[]) =>
  loadFacadeModule()["browserResetProfile"](...args)) as FacadeModule["browserResetProfile"];
export const browserScreenshotAction: FacadeModule["browserScreenshotAction"] = ((...args: any[]) =>
  loadFacadeModule()["browserScreenshotAction"](
    ...args,
  )) as FacadeModule["browserScreenshotAction"];
export const browserSnapshot: FacadeModule["browserSnapshot"] = ((...args: any[]) =>
  loadFacadeModule()["browserSnapshot"](...args)) as FacadeModule["browserSnapshot"];
export const browserStart: FacadeModule["browserStart"] = ((...args: any[]) =>
  loadFacadeModule()["browserStart"](...args)) as FacadeModule["browserStart"];
export const browserStatus: FacadeModule["browserStatus"] = ((...args: any[]) =>
  loadFacadeModule()["browserStatus"](...args)) as FacadeModule["browserStatus"];
export const browserStop: FacadeModule["browserStop"] = ((...args: any[]) =>
  loadFacadeModule()["browserStop"](...args)) as FacadeModule["browserStop"];
export const browserTabAction: FacadeModule["browserTabAction"] = ((...args: any[]) =>
  loadFacadeModule()["browserTabAction"](...args)) as FacadeModule["browserTabAction"];
export const browserTabs: FacadeModule["browserTabs"] = ((...args: any[]) =>
  loadFacadeModule()["browserTabs"](...args)) as FacadeModule["browserTabs"];
export const closeTrackedBrowserTabsForSessions: FacadeModule["closeTrackedBrowserTabsForSessions"] =
  ((...args: any[]) =>
    loadFacadeModule()["closeTrackedBrowserTabsForSessions"](
      ...args,
    )) as FacadeModule["closeTrackedBrowserTabsForSessions"];
export const createBrowserControlContext: FacadeModule["createBrowserControlContext"] = ((
  ...args
) =>
  loadFacadeModule()["createBrowserControlContext"](
    ...args,
  )) as FacadeModule["createBrowserControlContext"];
export const createBrowserPluginService: FacadeModule["createBrowserPluginService"] = ((...args: any[]) =>
  loadFacadeModule()["createBrowserPluginService"](
    ...args,
  )) as FacadeModule["createBrowserPluginService"];
export const createBrowserRouteContext: FacadeModule["createBrowserRouteContext"] = ((...args: any[]) =>
  loadFacadeModule()["createBrowserRouteContext"](
    ...args,
  )) as FacadeModule["createBrowserRouteContext"];
export const createBrowserRouteDispatcher: FacadeModule["createBrowserRouteDispatcher"] = ((
  ...args
) =>
  loadFacadeModule()["createBrowserRouteDispatcher"](
    ...args,
  )) as FacadeModule["createBrowserRouteDispatcher"];
export const createBrowserRuntimeState: FacadeModule["createBrowserRuntimeState"] = ((...args: any[]) =>
  loadFacadeModule()["createBrowserRuntimeState"](
    ...args,
  )) as FacadeModule["createBrowserRuntimeState"];
export const createBrowserTool: FacadeModule["createBrowserTool"] = ((...args: any[]) =>
  loadFacadeModule()["createBrowserTool"](...args)) as FacadeModule["createBrowserTool"];
export const definePluginEntry: FacadeModule["definePluginEntry"] = ((...args: any[]) =>
  loadFacadeModule()["definePluginEntry"](...args)) as FacadeModule["definePluginEntry"];
export const ensureBrowserControlAuth: FacadeModule["ensureBrowserControlAuth"] = ((...args: any[]) =>
  loadFacadeModule()["ensureBrowserControlAuth"](
    ...args,
  )) as FacadeModule["ensureBrowserControlAuth"];
export const getBrowserControlState: FacadeModule["getBrowserControlState"] = ((...args: any[]) =>
  loadFacadeModule()["getBrowserControlState"](...args)) as FacadeModule["getBrowserControlState"];
export const getBrowserProfileCapabilities: FacadeModule["getBrowserProfileCapabilities"] = ((
  ...args
) =>
  loadFacadeModule()["getBrowserProfileCapabilities"](
    ...args,
  )) as FacadeModule["getBrowserProfileCapabilities"];
export const handleBrowserGatewayRequest: FacadeModule["handleBrowserGatewayRequest"] = ((
  ...args
) =>
  loadFacadeModule()["handleBrowserGatewayRequest"](
    ...args,
  )) as FacadeModule["handleBrowserGatewayRequest"];
export const installBrowserAuthMiddleware: FacadeModule["installBrowserAuthMiddleware"] = ((
  ...args
) =>
  loadFacadeModule()["installBrowserAuthMiddleware"](
    ...args,
  )) as FacadeModule["installBrowserAuthMiddleware"];
export const installBrowserCommonMiddleware: FacadeModule["installBrowserCommonMiddleware"] = ((
  ...args
) =>
  loadFacadeModule()["installBrowserCommonMiddleware"](
    ...args,
  )) as FacadeModule["installBrowserCommonMiddleware"];
export const isPersistentBrowserProfileMutation: FacadeModule["isPersistentBrowserProfileMutation"] =
  ((...args: any[]) =>
    loadFacadeModule()["isPersistentBrowserProfileMutation"](
      ...args,
    )) as FacadeModule["isPersistentBrowserProfileMutation"];
export const movePathToTrash: FacadeModule["movePathToTrash"] = ((...args: any[]) =>
  loadFacadeModule()["movePathToTrash"](...args)) as FacadeModule["movePathToTrash"];
export const normalizeBrowserFormField: FacadeModule["normalizeBrowserFormField"] = ((...args: any[]) =>
  loadFacadeModule()["normalizeBrowserFormField"](
    ...args,
  )) as FacadeModule["normalizeBrowserFormField"];
export const normalizeBrowserFormFieldValue: FacadeModule["normalizeBrowserFormFieldValue"] = ((
  ...args
) =>
  loadFacadeModule()["normalizeBrowserFormFieldValue"](
    ...args,
  )) as FacadeModule["normalizeBrowserFormFieldValue"];
export const normalizeBrowserRequestPath: FacadeModule["normalizeBrowserRequestPath"] = ((
  ...args
) =>
  loadFacadeModule()["normalizeBrowserRequestPath"](
    ...args,
  )) as FacadeModule["normalizeBrowserRequestPath"];
export const parseBrowserMajorVersion: FacadeModule["parseBrowserMajorVersion"] = ((...args: any[]) =>
  loadFacadeModule()["parseBrowserMajorVersion"](
    ...args,
  )) as FacadeModule["parseBrowserMajorVersion"];
export const persistBrowserProxyFiles: FacadeModule["persistBrowserProxyFiles"] = ((...args: any[]) =>
  loadFacadeModule()["persistBrowserProxyFiles"](
    ...args,
  )) as FacadeModule["persistBrowserProxyFiles"];
export const readBrowserVersion: FacadeModule["readBrowserVersion"] = ((...args: any[]) =>
  loadFacadeModule()["readBrowserVersion"](...args)) as FacadeModule["readBrowserVersion"];
export const redactCdpUrl: FacadeModule["redactCdpUrl"] = ((...args: any[]) =>
  loadFacadeModule()["redactCdpUrl"](...args)) as FacadeModule["redactCdpUrl"];
export const registerBrowserCli: FacadeModule["registerBrowserCli"] = ((...args: any[]) =>
  loadFacadeModule()["registerBrowserCli"](...args)) as FacadeModule["registerBrowserCli"];
export const registerBrowserRoutes: FacadeModule["registerBrowserRoutes"] = ((...args: any[]) =>
  loadFacadeModule()["registerBrowserRoutes"](...args)) as FacadeModule["registerBrowserRoutes"];
export const resolveBrowserConfig: FacadeModule["resolveBrowserConfig"] = ((...args: any[]) =>
  loadFacadeModule()["resolveBrowserConfig"](...args)) as FacadeModule["resolveBrowserConfig"];
export const resolveBrowserControlAuth: FacadeModule["resolveBrowserControlAuth"] = ((...args: any[]) =>
  loadFacadeModule()["resolveBrowserControlAuth"](
    ...args,
  )) as FacadeModule["resolveBrowserControlAuth"];
export const resolveExistingPathsWithinRoot: FacadeModule["resolveExistingPathsWithinRoot"] = ((
  ...args
) =>
  loadFacadeModule()["resolveExistingPathsWithinRoot"](
    ...args,
  )) as FacadeModule["resolveExistingPathsWithinRoot"];
export const resolveGoogleChromeExecutableForPlatform: FacadeModule["resolveGoogleChromeExecutableForPlatform"] =
  ((...args: any[]) =>
    loadFacadeModule()["resolveGoogleChromeExecutableForPlatform"](
      ...args,
    )) as FacadeModule["resolveGoogleChromeExecutableForPlatform"];
export const resolveProfile: FacadeModule["resolveProfile"] = ((...args: any[]) =>
  loadFacadeModule()["resolveProfile"](...args)) as FacadeModule["resolveProfile"];
export const resolveRequestedBrowserProfile: FacadeModule["resolveRequestedBrowserProfile"] = ((
  ...args
) =>
  loadFacadeModule()["resolveRequestedBrowserProfile"](
    ...args,
  )) as FacadeModule["resolveRequestedBrowserProfile"];
export const runBrowserProxyCommand: FacadeModule["runBrowserProxyCommand"] = ((...args: any[]) =>
  loadFacadeModule()["runBrowserProxyCommand"](...args)) as FacadeModule["runBrowserProxyCommand"];
export const startBrowserBridgeServer: FacadeModule["startBrowserBridgeServer"] = ((...args: any[]) =>
  loadFacadeModule()["startBrowserBridgeServer"](
    ...args,
  )) as FacadeModule["startBrowserBridgeServer"];
export const startBrowserControlServiceFromConfig: FacadeModule["startBrowserControlServiceFromConfig"] =
  ((...args: any[]) =>
    loadFacadeModule()["startBrowserControlServiceFromConfig"](
      ...args,
    )) as FacadeModule["startBrowserControlServiceFromConfig"];
export const stopBrowserBridgeServer: FacadeModule["stopBrowserBridgeServer"] = ((...args: any[]) =>
  loadFacadeModule()["stopBrowserBridgeServer"](
    ...args,
  )) as FacadeModule["stopBrowserBridgeServer"];
export const stopBrowserControlService: FacadeModule["stopBrowserControlService"] = ((...args: any[]) =>
  loadFacadeModule()["stopBrowserControlService"](
    ...args,
  )) as FacadeModule["stopBrowserControlService"];
export const stopBrowserRuntime: FacadeModule["stopBrowserRuntime"] = ((...args: any[]) =>
  loadFacadeModule()["stopBrowserRuntime"](...args)) as FacadeModule["stopBrowserRuntime"];
export const trackSessionBrowserTab: FacadeModule["trackSessionBrowserTab"] = ((...args: any[]) =>
  loadFacadeModule()["trackSessionBrowserTab"](...args)) as FacadeModule["trackSessionBrowserTab"];
export const untrackSessionBrowserTab: FacadeModule["untrackSessionBrowserTab"] = ((...args: any[]) =>
  loadFacadeModule()["untrackSessionBrowserTab"](
    ...args,
  )) as FacadeModule["untrackSessionBrowserTab"];
export type BrowserBridge = FacadeEntry["types"]["BrowserBridge"];
export type BrowserCreateProfileResult = FacadeEntry["types"]["BrowserCreateProfileResult"];
export type BrowserDeleteProfileResult = FacadeEntry["types"]["BrowserDeleteProfileResult"];
export type BrowserExecutable = FacadeEntry["types"]["BrowserExecutable"];
export type BrowserFormField = FacadeEntry["types"]["BrowserFormField"];
export type BrowserResetProfileResult = FacadeEntry["types"]["BrowserResetProfileResult"];
export type BrowserRouteRegistrar = FacadeEntry["types"]["BrowserRouteRegistrar"];
export type BrowserServerState = FacadeEntry["types"]["BrowserServerState"];
export type BrowserStatus = FacadeEntry["types"]["BrowserStatus"];
export type BrowserTab = FacadeEntry["types"]["BrowserTab"];
export type BrowserTransport = FacadeEntry["types"]["BrowserTransport"];
export type VoraPluginApi = FacadeEntry["types"]["VoraPluginApi"];
export type VoraPluginToolContext = FacadeEntry["types"]["VoraPluginToolContext"];
export type VoraPluginToolFactory = FacadeEntry["types"]["VoraPluginToolFactory"];
export type ProfileStatus = FacadeEntry["types"]["ProfileStatus"];
export type ResolvedBrowserConfig = FacadeEntry["types"]["ResolvedBrowserConfig"];
export type ResolvedBrowserProfile = FacadeEntry["types"]["ResolvedBrowserProfile"];
export type SnapshotResult = FacadeEntry["types"]["SnapshotResult"];
