// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["google"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "google",
    artifactBasename: "api.js",
  });
}
export const applyGoogleGeminiModelDefault: FacadeModule["applyGoogleGeminiModelDefault"] = ((
  ...args
) =>
  loadFacadeModule()["applyGoogleGeminiModelDefault"](
    ...args,
  )) as FacadeModule["applyGoogleGeminiModelDefault"];
export const DEFAULT_GOOGLE_API_BASE_URL: FacadeModule["DEFAULT_GOOGLE_API_BASE_URL"] =
  loadFacadeModule()["DEFAULT_GOOGLE_API_BASE_URL"];
export const GOOGLE_GEMINI_DEFAULT_MODEL: FacadeModule["GOOGLE_GEMINI_DEFAULT_MODEL"] =
  loadFacadeModule()["GOOGLE_GEMINI_DEFAULT_MODEL"];
export const isGoogleGenerativeAiApi: FacadeModule["isGoogleGenerativeAiApi"] = ((...args: any[]) =>
  loadFacadeModule()["isGoogleGenerativeAiApi"](
    ...args,
  )) as FacadeModule["isGoogleGenerativeAiApi"];
export const normalizeAntigravityModelId: FacadeModule["normalizeAntigravityModelId"] = ((
  ...args
) =>
  loadFacadeModule()["normalizeAntigravityModelId"](
    ...args,
  )) as FacadeModule["normalizeAntigravityModelId"];
export const normalizeGoogleApiBaseUrl: FacadeModule["normalizeGoogleApiBaseUrl"] = ((...args: any[]) =>
  loadFacadeModule()["normalizeGoogleApiBaseUrl"](
    ...args,
  )) as FacadeModule["normalizeGoogleApiBaseUrl"];
export const normalizeGoogleGenerativeAiBaseUrl: FacadeModule["normalizeGoogleGenerativeAiBaseUrl"] =
  ((...args: any[]) =>
    loadFacadeModule()["normalizeGoogleGenerativeAiBaseUrl"](
      ...args,
    )) as FacadeModule["normalizeGoogleGenerativeAiBaseUrl"];
export const normalizeGoogleModelId: FacadeModule["normalizeGoogleModelId"] = ((...args: any[]) =>
  loadFacadeModule()["normalizeGoogleModelId"](...args)) as FacadeModule["normalizeGoogleModelId"];
export const normalizeGoogleProviderConfig: FacadeModule["normalizeGoogleProviderConfig"] = ((
  ...args
) =>
  loadFacadeModule()["normalizeGoogleProviderConfig"](
    ...args,
  )) as FacadeModule["normalizeGoogleProviderConfig"];
export const parseGeminiAuth: FacadeModule["parseGeminiAuth"] = ((...args: any[]) =>
  loadFacadeModule()["parseGeminiAuth"](...args)) as FacadeModule["parseGeminiAuth"];
export const resolveGoogleGenerativeAiApiOrigin: FacadeModule["resolveGoogleGenerativeAiApiOrigin"] =
  ((...args: any[]) =>
    loadFacadeModule()["resolveGoogleGenerativeAiApiOrigin"](
      ...args,
    )) as FacadeModule["resolveGoogleGenerativeAiApiOrigin"];
export const resolveGoogleGenerativeAiTransport: FacadeModule["resolveGoogleGenerativeAiTransport"] =
  ((...args: any[]) =>
    loadFacadeModule()["resolveGoogleGenerativeAiTransport"](
      ...args,
    )) as FacadeModule["resolveGoogleGenerativeAiTransport"];
export const shouldNormalizeGoogleProviderConfig: FacadeModule["shouldNormalizeGoogleProviderConfig"] =
  ((...args: any[]) =>
    loadFacadeModule()["shouldNormalizeGoogleProviderConfig"](
      ...args,
    )) as FacadeModule["shouldNormalizeGoogleProviderConfig"];
export const shouldNormalizeGoogleGenerativeAiProviderConfig: FacadeModule["shouldNormalizeGoogleGenerativeAiProviderConfig"] =
  ((...args: any[]) =>
    loadFacadeModule()["shouldNormalizeGoogleGenerativeAiProviderConfig"](
      ...args,
    )) as FacadeModule["shouldNormalizeGoogleGenerativeAiProviderConfig"];
