// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["ollama"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "ollama",
    artifactBasename: "runtime-api.js",
  });
}
export const buildAssistantMessage: FacadeModule["buildAssistantMessage"] = ((...args: any[]) =>
  loadFacadeModule()["buildAssistantMessage"](...args)) as FacadeModule["buildAssistantMessage"];
export const buildOllamaChatRequest: FacadeModule["buildOllamaChatRequest"] = ((...args: any[]) =>
  loadFacadeModule()["buildOllamaChatRequest"](...args)) as FacadeModule["buildOllamaChatRequest"];
export const convertToOllamaMessages: FacadeModule["convertToOllamaMessages"] = ((...args: any[]) =>
  loadFacadeModule()["convertToOllamaMessages"](
    ...args,
  )) as FacadeModule["convertToOllamaMessages"];
export const createOllamaEmbeddingProvider: FacadeModule["createOllamaEmbeddingProvider"] = ((
  ...args
) =>
  loadFacadeModule()["createOllamaEmbeddingProvider"](
    ...args,
  )) as FacadeModule["createOllamaEmbeddingProvider"];
export const createConfiguredOllamaCompatNumCtxWrapper: FacadeModule["createConfiguredOllamaCompatNumCtxWrapper"] =
  ((...args: any[]) =>
    loadFacadeModule()["createConfiguredOllamaCompatNumCtxWrapper"](
      ...args,
    )) as FacadeModule["createConfiguredOllamaCompatNumCtxWrapper"];
export const createConfiguredOllamaCompatStreamWrapper: FacadeModule["createConfiguredOllamaCompatStreamWrapper"] =
  ((...args: any[]) =>
    loadFacadeModule()["createConfiguredOllamaCompatStreamWrapper"](
      ...args,
    )) as FacadeModule["createConfiguredOllamaCompatStreamWrapper"];
export const createConfiguredOllamaStreamFn: FacadeModule["createConfiguredOllamaStreamFn"] = ((
  ...args
) =>
  loadFacadeModule()["createConfiguredOllamaStreamFn"](
    ...args,
  )) as FacadeModule["createConfiguredOllamaStreamFn"];
export const createOllamaStreamFn: FacadeModule["createOllamaStreamFn"] = ((...args: any[]) =>
  loadFacadeModule()["createOllamaStreamFn"](...args)) as FacadeModule["createOllamaStreamFn"];
export const DEFAULT_OLLAMA_EMBEDDING_MODEL: FacadeModule["DEFAULT_OLLAMA_EMBEDDING_MODEL"] =
  loadFacadeModule()["DEFAULT_OLLAMA_EMBEDDING_MODEL"];
export const isOllamaCompatProvider: FacadeModule["isOllamaCompatProvider"] = ((...args: any[]) =>
  loadFacadeModule()["isOllamaCompatProvider"](...args)) as FacadeModule["isOllamaCompatProvider"];
export const OLLAMA_NATIVE_BASE_URL: FacadeModule["OLLAMA_NATIVE_BASE_URL"] =
  loadFacadeModule()["OLLAMA_NATIVE_BASE_URL"];
export const parseNdjsonStream: FacadeModule["parseNdjsonStream"] = ((...args: any[]) =>
  loadFacadeModule()["parseNdjsonStream"](...args)) as FacadeModule["parseNdjsonStream"];
export const resolveOllamaBaseUrlForRun: FacadeModule["resolveOllamaBaseUrlForRun"] = ((...args: any[]) =>
  loadFacadeModule()["resolveOllamaBaseUrlForRun"](
    ...args,
  )) as FacadeModule["resolveOllamaBaseUrlForRun"];
export const resolveOllamaCompatNumCtxEnabled: FacadeModule["resolveOllamaCompatNumCtxEnabled"] = ((
  ...args
) =>
  loadFacadeModule()["resolveOllamaCompatNumCtxEnabled"](
    ...args,
  )) as FacadeModule["resolveOllamaCompatNumCtxEnabled"];
export const shouldInjectOllamaCompatNumCtx: FacadeModule["shouldInjectOllamaCompatNumCtx"] = ((
  ...args
) =>
  loadFacadeModule()["shouldInjectOllamaCompatNumCtx"](
    ...args,
  )) as FacadeModule["shouldInjectOllamaCompatNumCtx"];
export const wrapOllamaCompatNumCtx: FacadeModule["wrapOllamaCompatNumCtx"] = ((...args: any[]) =>
  loadFacadeModule()["wrapOllamaCompatNumCtx"](...args)) as FacadeModule["wrapOllamaCompatNumCtx"];
export type OllamaEmbeddingClient = FacadeEntry["types"]["OllamaEmbeddingClient"];
export type OllamaEmbeddingProvider = FacadeEntry["types"]["OllamaEmbeddingProvider"];
