// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["signal-surface"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeObjectValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "signal",
    artifactBasename: "api.js",
  });
}
export const isSignalSenderAllowed: FacadeModule["isSignalSenderAllowed"] = ((...args: any[]) =>
  loadFacadeModule()["isSignalSenderAllowed"](...args)) as FacadeModule["isSignalSenderAllowed"];
export const listEnabledSignalAccounts: FacadeModule["listEnabledSignalAccounts"] = ((...args: any[]) =>
  loadFacadeModule()["listEnabledSignalAccounts"](
    ...args,
  )) as FacadeModule["listEnabledSignalAccounts"];
export const listSignalAccountIds: FacadeModule["listSignalAccountIds"] = ((...args: any[]) =>
  loadFacadeModule()["listSignalAccountIds"](...args)) as FacadeModule["listSignalAccountIds"];
export const monitorSignalProvider: FacadeModule["monitorSignalProvider"] = ((...args: any[]) =>
  loadFacadeModule()["monitorSignalProvider"](...args)) as FacadeModule["monitorSignalProvider"];
export const probeSignal: FacadeModule["probeSignal"] = ((...args: any[]) =>
  loadFacadeModule()["probeSignal"](...args)) as FacadeModule["probeSignal"];
export const removeReactionSignal: FacadeModule["removeReactionSignal"] = ((...args: any[]) =>
  loadFacadeModule()["removeReactionSignal"](...args)) as FacadeModule["removeReactionSignal"];
export const resolveDefaultSignalAccountId: FacadeModule["resolveDefaultSignalAccountId"] = ((
  ...args
) =>
  loadFacadeModule()["resolveDefaultSignalAccountId"](
    ...args,
  )) as FacadeModule["resolveDefaultSignalAccountId"];
export const resolveSignalReactionLevel: FacadeModule["resolveSignalReactionLevel"] = ((...args: any[]) =>
  loadFacadeModule()["resolveSignalReactionLevel"](
    ...args,
  )) as FacadeModule["resolveSignalReactionLevel"];
export const sendMessageSignal: FacadeModule["sendMessageSignal"] = ((...args: any[]) =>
  loadFacadeModule()["sendMessageSignal"](...args)) as FacadeModule["sendMessageSignal"];
export const sendReactionSignal: FacadeModule["sendReactionSignal"] = ((...args: any[]) =>
  loadFacadeModule()["sendReactionSignal"](...args)) as FacadeModule["sendReactionSignal"];
export const signalMessageActions: FacadeModule["signalMessageActions"] =
  createLazyFacadeObjectValue(
    () => loadFacadeModule()["signalMessageActions"] as object,
  ) as FacadeModule["signalMessageActions"];
export type ResolvedSignalAccount = FacadeEntry["types"]["ResolvedSignalAccount"];
export type SignalProbe = FacadeEntry["types"]["SignalProbe"];
export type SignalSender = FacadeEntry["types"]["SignalSender"];
