// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["slack-runtime-surface"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "slack",
    artifactBasename: "runtime-api.js",
  });
}
export const handleSlackAction: FacadeModule["handleSlackAction"] = ((...args: any[]) =>
  loadFacadeModule()["handleSlackAction"](...args)) as FacadeModule["handleSlackAction"];
export const listSlackDirectoryGroupsLive: FacadeModule["listSlackDirectoryGroupsLive"] = ((
  ...args
) =>
  loadFacadeModule()["listSlackDirectoryGroupsLive"](
    ...args,
  )) as FacadeModule["listSlackDirectoryGroupsLive"];
export const listSlackDirectoryPeersLive: FacadeModule["listSlackDirectoryPeersLive"] = ((
  ...args
) =>
  loadFacadeModule()["listSlackDirectoryPeersLive"](
    ...args,
  )) as FacadeModule["listSlackDirectoryPeersLive"];
export const monitorSlackProvider: FacadeModule["monitorSlackProvider"] = ((...args: any[]) =>
  loadFacadeModule()["monitorSlackProvider"](...args)) as FacadeModule["monitorSlackProvider"];
export const probeSlack: FacadeModule["probeSlack"] = ((...args: any[]) =>
  loadFacadeModule()["probeSlack"](...args)) as FacadeModule["probeSlack"];
export const resolveSlackChannelAllowlist: FacadeModule["resolveSlackChannelAllowlist"] = ((
  ...args
) =>
  loadFacadeModule()["resolveSlackChannelAllowlist"](
    ...args,
  )) as FacadeModule["resolveSlackChannelAllowlist"];
export const resolveSlackUserAllowlist: FacadeModule["resolveSlackUserAllowlist"] = ((...args: any[]) =>
  loadFacadeModule()["resolveSlackUserAllowlist"](
    ...args,
  )) as FacadeModule["resolveSlackUserAllowlist"];
export const sendMessageSlack: FacadeModule["sendMessageSlack"] = ((...args: any[]) =>
  loadFacadeModule()["sendMessageSlack"](...args)) as FacadeModule["sendMessageSlack"];
export type SlackActionContext = FacadeEntry["types"]["SlackActionContext"];
