// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["slack-surface"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "slack",
    artifactBasename: "api.js",
  });
}
export const buildSlackThreadingToolContext: FacadeModule["buildSlackThreadingToolContext"] = ((
  ...args
) =>
  loadFacadeModule()["buildSlackThreadingToolContext"](
    ...args,
  )) as FacadeModule["buildSlackThreadingToolContext"];
export const createSlackWebClient: FacadeModule["createSlackWebClient"] = ((...args: any[]) =>
  loadFacadeModule()["createSlackWebClient"](...args)) as FacadeModule["createSlackWebClient"];
export const deleteSlackMessage: FacadeModule["deleteSlackMessage"] = ((...args: any[]) =>
  loadFacadeModule()["deleteSlackMessage"](...args)) as FacadeModule["deleteSlackMessage"];
export const downloadSlackFile: FacadeModule["downloadSlackFile"] = ((...args: any[]) =>
  loadFacadeModule()["downloadSlackFile"](...args)) as FacadeModule["downloadSlackFile"];
export const editSlackMessage: FacadeModule["editSlackMessage"] = ((...args: any[]) =>
  loadFacadeModule()["editSlackMessage"](...args)) as FacadeModule["editSlackMessage"];
export const extractSlackToolSend: FacadeModule["extractSlackToolSend"] = ((...args: any[]) =>
  loadFacadeModule()["extractSlackToolSend"](...args)) as FacadeModule["extractSlackToolSend"];
export const getSlackMemberInfo: FacadeModule["getSlackMemberInfo"] = ((...args: any[]) =>
  loadFacadeModule()["getSlackMemberInfo"](...args)) as FacadeModule["getSlackMemberInfo"];
export const handleSlackHttpRequest: FacadeModule["handleSlackHttpRequest"] = ((...args: any[]) =>
  loadFacadeModule()["handleSlackHttpRequest"](...args)) as FacadeModule["handleSlackHttpRequest"];
export const inspectSlackAccount: FacadeModule["inspectSlackAccount"] = ((...args: any[]) =>
  loadFacadeModule()["inspectSlackAccount"](...args)) as FacadeModule["inspectSlackAccount"];
export const isSlackInteractiveRepliesEnabled: FacadeModule["isSlackInteractiveRepliesEnabled"] = ((
  ...args
) =>
  loadFacadeModule()["isSlackInteractiveRepliesEnabled"](
    ...args,
  )) as FacadeModule["isSlackInteractiveRepliesEnabled"];
export const listEnabledSlackAccounts: FacadeModule["listEnabledSlackAccounts"] = ((...args: any[]) =>
  loadFacadeModule()["listEnabledSlackAccounts"](
    ...args,
  )) as FacadeModule["listEnabledSlackAccounts"];
export const listSlackAccountIds: FacadeModule["listSlackAccountIds"] = ((...args: any[]) =>
  loadFacadeModule()["listSlackAccountIds"](...args)) as FacadeModule["listSlackAccountIds"];
export const listSlackDirectoryGroupsFromConfig: FacadeModule["listSlackDirectoryGroupsFromConfig"] =
  ((...args: any[]) =>
    loadFacadeModule()["listSlackDirectoryGroupsFromConfig"](
      ...args,
    )) as FacadeModule["listSlackDirectoryGroupsFromConfig"];
export const listSlackDirectoryPeersFromConfig: FacadeModule["listSlackDirectoryPeersFromConfig"] =
  ((...args: any[]) =>
    loadFacadeModule()["listSlackDirectoryPeersFromConfig"](
      ...args,
    )) as FacadeModule["listSlackDirectoryPeersFromConfig"];
export const listSlackEmojis: FacadeModule["listSlackEmojis"] = ((...args: any[]) =>
  loadFacadeModule()["listSlackEmojis"](...args)) as FacadeModule["listSlackEmojis"];
export const listSlackMessageActions: FacadeModule["listSlackMessageActions"] = ((...args: any[]) =>
  loadFacadeModule()["listSlackMessageActions"](
    ...args,
  )) as FacadeModule["listSlackMessageActions"];
export const listSlackPins: FacadeModule["listSlackPins"] = ((...args: any[]) =>
  loadFacadeModule()["listSlackPins"](...args)) as FacadeModule["listSlackPins"];
export const listSlackReactions: FacadeModule["listSlackReactions"] = ((...args: any[]) =>
  loadFacadeModule()["listSlackReactions"](...args)) as FacadeModule["listSlackReactions"];
export const normalizeAllowListLower: FacadeModule["normalizeAllowListLower"] = ((...args: any[]) =>
  loadFacadeModule()["normalizeAllowListLower"](
    ...args,
  )) as FacadeModule["normalizeAllowListLower"];
export const parseSlackBlocksInput: FacadeModule["parseSlackBlocksInput"] = ((...args: any[]) =>
  loadFacadeModule()["parseSlackBlocksInput"](...args)) as FacadeModule["parseSlackBlocksInput"];
export const recordSlackThreadParticipation: FacadeModule["recordSlackThreadParticipation"] = ((
  ...args
) =>
  loadFacadeModule()["recordSlackThreadParticipation"](
    ...args,
  )) as FacadeModule["recordSlackThreadParticipation"];
export const resolveDefaultSlackAccountId: FacadeModule["resolveDefaultSlackAccountId"] = ((
  ...args
) =>
  loadFacadeModule()["resolveDefaultSlackAccountId"](
    ...args,
  )) as FacadeModule["resolveDefaultSlackAccountId"];
export const resolveSlackAutoThreadId: FacadeModule["resolveSlackAutoThreadId"] = ((...args: any[]) =>
  loadFacadeModule()["resolveSlackAutoThreadId"](
    ...args,
  )) as FacadeModule["resolveSlackAutoThreadId"];
export const resolveSlackGroupRequireMention: FacadeModule["resolveSlackGroupRequireMention"] = ((
  ...args
) =>
  loadFacadeModule()["resolveSlackGroupRequireMention"](
    ...args,
  )) as FacadeModule["resolveSlackGroupRequireMention"];
export const resolveSlackRuntimeGroupPolicy: FacadeModule["resolveSlackRuntimeGroupPolicy"] = ((
  ...args
) =>
  loadFacadeModule()["resolveSlackRuntimeGroupPolicy"](
    ...args,
  )) as FacadeModule["resolveSlackRuntimeGroupPolicy"];
export const resolveSlackGroupToolPolicy: FacadeModule["resolveSlackGroupToolPolicy"] = ((
  ...args
) =>
  loadFacadeModule()["resolveSlackGroupToolPolicy"](
    ...args,
  )) as FacadeModule["resolveSlackGroupToolPolicy"];
export const resolveSlackReplyToMode: FacadeModule["resolveSlackReplyToMode"] = ((...args: any[]) =>
  loadFacadeModule()["resolveSlackReplyToMode"](
    ...args,
  )) as FacadeModule["resolveSlackReplyToMode"];
export const sendSlackMessage: FacadeModule["sendSlackMessage"] = ((...args: any[]) =>
  loadFacadeModule()["sendSlackMessage"](...args)) as FacadeModule["sendSlackMessage"];
export const pinSlackMessage: FacadeModule["pinSlackMessage"] = ((...args: any[]) =>
  loadFacadeModule()["pinSlackMessage"](...args)) as FacadeModule["pinSlackMessage"];
export const reactSlackMessage: FacadeModule["reactSlackMessage"] = ((...args: any[]) =>
  loadFacadeModule()["reactSlackMessage"](...args)) as FacadeModule["reactSlackMessage"];
export const readSlackMessages: FacadeModule["readSlackMessages"] = ((...args: any[]) =>
  loadFacadeModule()["readSlackMessages"](...args)) as FacadeModule["readSlackMessages"];
export const removeOwnSlackReactions: FacadeModule["removeOwnSlackReactions"] = ((...args: any[]) =>
  loadFacadeModule()["removeOwnSlackReactions"](
    ...args,
  )) as FacadeModule["removeOwnSlackReactions"];
export const removeSlackReaction: FacadeModule["removeSlackReaction"] = ((...args: any[]) =>
  loadFacadeModule()["removeSlackReaction"](...args)) as FacadeModule["removeSlackReaction"];
export const unpinSlackMessage: FacadeModule["unpinSlackMessage"] = ((...args: any[]) =>
  loadFacadeModule()["unpinSlackMessage"](...args)) as FacadeModule["unpinSlackMessage"];
export type InspectedSlackAccount = FacadeEntry["types"]["InspectedSlackAccount"];
export type ResolvedSlackAccount = FacadeEntry["types"]["ResolvedSlackAccount"];
export type SlackProbe = FacadeEntry["types"]["SlackProbe"];
