// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["telegram-surface"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "telegram",
    artifactBasename: "api.js",
  });
}
export const buildBrowseProvidersButton: FacadeModule["buildBrowseProvidersButton"] = ((...args: any[]) =>
  loadFacadeModule()["buildBrowseProvidersButton"](
    ...args,
  )) as FacadeModule["buildBrowseProvidersButton"];
export const buildModelsKeyboard: FacadeModule["buildModelsKeyboard"] = ((...args: any[]) =>
  loadFacadeModule()["buildModelsKeyboard"](...args)) as FacadeModule["buildModelsKeyboard"];
export const buildProviderKeyboard: FacadeModule["buildProviderKeyboard"] = ((...args: any[]) =>
  loadFacadeModule()["buildProviderKeyboard"](...args)) as FacadeModule["buildProviderKeyboard"];
export const buildTelegramGroupPeerId: FacadeModule["buildTelegramGroupPeerId"] = ((...args: any[]) =>
  loadFacadeModule()["buildTelegramGroupPeerId"](
    ...args,
  )) as FacadeModule["buildTelegramGroupPeerId"];
export const calculateTotalPages: FacadeModule["calculateTotalPages"] = ((...args: any[]) =>
  loadFacadeModule()["calculateTotalPages"](...args)) as FacadeModule["calculateTotalPages"];
export const createTelegramActionGate: FacadeModule["createTelegramActionGate"] = ((...args: any[]) =>
  loadFacadeModule()["createTelegramActionGate"](
    ...args,
  )) as FacadeModule["createTelegramActionGate"];
export const fetchTelegramChatId: FacadeModule["fetchTelegramChatId"] = ((...args: any[]) =>
  loadFacadeModule()["fetchTelegramChatId"](...args)) as FacadeModule["fetchTelegramChatId"];
export const getCacheStats: FacadeModule["getCacheStats"] = ((...args: any[]) =>
  loadFacadeModule()["getCacheStats"](...args)) as FacadeModule["getCacheStats"];
export const getModelsPageSize: FacadeModule["getModelsPageSize"] = ((...args: any[]) =>
  loadFacadeModule()["getModelsPageSize"](...args)) as FacadeModule["getModelsPageSize"];
export const inspectTelegramAccount: FacadeModule["inspectTelegramAccount"] = ((...args: any[]) =>
  loadFacadeModule()["inspectTelegramAccount"](...args)) as FacadeModule["inspectTelegramAccount"];
export const isTelegramExecApprovalApprover: FacadeModule["isTelegramExecApprovalApprover"] = ((
  ...args
) =>
  loadFacadeModule()["isTelegramExecApprovalApprover"](
    ...args,
  )) as FacadeModule["isTelegramExecApprovalApprover"];
export const isTelegramExecApprovalAuthorizedSender: FacadeModule["isTelegramExecApprovalAuthorizedSender"] =
  ((...args: any[]) =>
    loadFacadeModule()["isTelegramExecApprovalAuthorizedSender"](
      ...args,
    )) as FacadeModule["isTelegramExecApprovalAuthorizedSender"];
export const isTelegramExecApprovalClientEnabled: FacadeModule["isTelegramExecApprovalClientEnabled"] =
  ((...args: any[]) =>
    loadFacadeModule()["isTelegramExecApprovalClientEnabled"](
      ...args,
    )) as FacadeModule["isTelegramExecApprovalClientEnabled"];
export const isTelegramExecApprovalTargetRecipient: FacadeModule["isTelegramExecApprovalTargetRecipient"] =
  ((...args: any[]) =>
    loadFacadeModule()["isTelegramExecApprovalTargetRecipient"](
      ...args,
    )) as FacadeModule["isTelegramExecApprovalTargetRecipient"];
export const listTelegramAccountIds: FacadeModule["listTelegramAccountIds"] = ((...args: any[]) =>
  loadFacadeModule()["listTelegramAccountIds"](...args)) as FacadeModule["listTelegramAccountIds"];
export const listTelegramDirectoryGroupsFromConfig: FacadeModule["listTelegramDirectoryGroupsFromConfig"] =
  ((...args: any[]) =>
    loadFacadeModule()["listTelegramDirectoryGroupsFromConfig"](
      ...args,
    )) as FacadeModule["listTelegramDirectoryGroupsFromConfig"];
export const listTelegramDirectoryPeersFromConfig: FacadeModule["listTelegramDirectoryPeersFromConfig"] =
  ((...args: any[]) =>
    loadFacadeModule()["listTelegramDirectoryPeersFromConfig"](
      ...args,
    )) as FacadeModule["listTelegramDirectoryPeersFromConfig"];
export const looksLikeTelegramTargetId: FacadeModule["looksLikeTelegramTargetId"] = ((...args: any[]) =>
  loadFacadeModule()["looksLikeTelegramTargetId"](
    ...args,
  )) as FacadeModule["looksLikeTelegramTargetId"];
export const lookupTelegramChatId: FacadeModule["lookupTelegramChatId"] = ((...args: any[]) =>
  loadFacadeModule()["lookupTelegramChatId"](...args)) as FacadeModule["lookupTelegramChatId"];
export const normalizeTelegramMessagingTarget: FacadeModule["normalizeTelegramMessagingTarget"] = ((
  ...args
) =>
  loadFacadeModule()["normalizeTelegramMessagingTarget"](
    ...args,
  )) as FacadeModule["normalizeTelegramMessagingTarget"];
export const parseTelegramReplyToMessageId: FacadeModule["parseTelegramReplyToMessageId"] = ((
  ...args
) =>
  loadFacadeModule()["parseTelegramReplyToMessageId"](
    ...args,
  )) as FacadeModule["parseTelegramReplyToMessageId"];
export const parseTelegramTarget: FacadeModule["parseTelegramTarget"] = ((...args: any[]) =>
  loadFacadeModule()["parseTelegramTarget"](...args)) as FacadeModule["parseTelegramTarget"];
export const parseTelegramThreadId: FacadeModule["parseTelegramThreadId"] = ((...args: any[]) =>
  loadFacadeModule()["parseTelegramThreadId"](...args)) as FacadeModule["parseTelegramThreadId"];
export const resolveTelegramAutoThreadId: FacadeModule["resolveTelegramAutoThreadId"] = ((
  ...args
) =>
  loadFacadeModule()["resolveTelegramAutoThreadId"](
    ...args,
  )) as FacadeModule["resolveTelegramAutoThreadId"];
export const resolveTelegramGroupRequireMention: FacadeModule["resolveTelegramGroupRequireMention"] =
  ((...args: any[]) =>
    loadFacadeModule()["resolveTelegramGroupRequireMention"](
      ...args,
    )) as FacadeModule["resolveTelegramGroupRequireMention"];
export const resolveTelegramGroupToolPolicy: FacadeModule["resolveTelegramGroupToolPolicy"] = ((
  ...args
) =>
  loadFacadeModule()["resolveTelegramGroupToolPolicy"](
    ...args,
  )) as FacadeModule["resolveTelegramGroupToolPolicy"];
export const resolveTelegramInlineButtonsScope: FacadeModule["resolveTelegramInlineButtonsScope"] =
  ((...args: any[]) =>
    loadFacadeModule()["resolveTelegramInlineButtonsScope"](
      ...args,
    )) as FacadeModule["resolveTelegramInlineButtonsScope"];
export const resolveTelegramPollActionGateState: FacadeModule["resolveTelegramPollActionGateState"] =
  ((...args: any[]) =>
    loadFacadeModule()["resolveTelegramPollActionGateState"](
      ...args,
    )) as FacadeModule["resolveTelegramPollActionGateState"];
export const resolveTelegramReactionLevel: FacadeModule["resolveTelegramReactionLevel"] = ((
  ...args
) =>
  loadFacadeModule()["resolveTelegramReactionLevel"](
    ...args,
  )) as FacadeModule["resolveTelegramReactionLevel"];
export const resolveTelegramTargetChatType: FacadeModule["resolveTelegramTargetChatType"] = ((
  ...args
) =>
  loadFacadeModule()["resolveTelegramTargetChatType"](
    ...args,
  )) as FacadeModule["resolveTelegramTargetChatType"];
export const searchStickers: FacadeModule["searchStickers"] = ((...args: any[]) =>
  loadFacadeModule()["searchStickers"](...args)) as FacadeModule["searchStickers"];
export const sendTelegramPayloadMessages: FacadeModule["sendTelegramPayloadMessages"] = ((
  ...args
) =>
  loadFacadeModule()["sendTelegramPayloadMessages"](
    ...args,
  )) as FacadeModule["sendTelegramPayloadMessages"];
export type InspectedTelegramAccount = FacadeEntry["types"]["InspectedTelegramAccount"];
export type ProviderInfo = FacadeEntry["types"]["ProviderInfo"];
export type ResolvedTelegramAccount = FacadeEntry["types"]["ResolvedTelegramAccount"];
export type StickerMetadata = FacadeEntry["types"]["StickerMetadata"];
export type TelegramButtonStyle = FacadeEntry["types"]["TelegramButtonStyle"];
export type TelegramInlineButtons = FacadeEntry["types"]["TelegramInlineButtons"];
export type TelegramProbe = FacadeEntry["types"]["TelegramProbe"];
export type TelegramTokenResolution = FacadeEntry["types"]["TelegramTokenResolution"];
