export const browserCoreExamples = [
  "vora browser status",
  "vora browser start",
  "vora browser stop",
  "vora browser tabs",
  "vora browser open https://example.com",
  "vora browser focus abcd1234",
  "vora browser close abcd1234",
  "vora browser screenshot",
  "vora browser screenshot --full-page",
  "vora browser screenshot --ref 12",
  "vora browser snapshot",
  "vora browser snapshot --format aria --limit 200",
  "vora browser snapshot --efficient",
  "vora browser snapshot --labels",
];

export const browserActionExamples = [
  "vora browser navigate https://example.com",
  "vora browser resize 1280 720",
  "vora browser click 12 --double",
  'vora browser type 23 "hello" --submit',
  "vora browser press Enter",
  "vora browser hover 44",
  "vora browser drag 10 11",
  "vora browser select 9 OptionA OptionB",
  "vora browser upload /tmp/vora/uploads/file.pdf",
  'vora browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "vora browser dialog --accept",
  'vora browser wait --text "Done"',
  "vora browser evaluate --fn '(el) => el.textContent' --ref 7",
  "vora browser console --level error",
  "vora browser pdf",
];
